# Generated by Django 5.1.4 on 2024-12-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto', max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('tecologias', models.JSONField(help_text='Tecnologías del proyecto')),
                ('github_link', models.URLField(help_text='Link de Github', max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
