# Generated by Django 5.1.4 on 2024-12-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proyecto', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('github', models.URLField(help_text='Link de Github', max_length=255)),
                ('vsCode', models.URLField(help_text='Link de VSCode', max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='images')),
                ('technologies_title', models.CharField(help_text='titulo de la tecnologia', max_length=255)),
                ('technologies_isDisabled', models.BooleanField(default=False)),
                ('technologies_href', models.URLField(help_text='link de la tecnologia', max_length=255)),
                ('status_title', models.CharField(help_text='titulo del estado', max_length=255)),
            ],
        ),
    ]
