# Generated by Django 5.1.4 on 2024-12-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(help_text='titulo del estado', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tecnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies_title', models.CharField(help_text='titulo de la tecnologia', max_length=255)),
                ('technologies_isDisabled', models.BooleanField(default=False)),
                ('technologies_href', models.URLField(help_text='link de la tecnologia', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='portafolioprojects',
            name='status_title',
        ),
        migrations.RemoveField(
            model_name='portafolioprojects',
            name='technologies_href',
        ),
        migrations.RemoveField(
            model_name='portafolioprojects',
            name='technologies_isDisabled',
        ),
        migrations.RemoveField(
            model_name='portafolioprojects',
            name='technologies_title',
        ),
        migrations.AddField(
            model_name='portafolioprojects',
            name='Estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Portafolio_App.statusproject'),
        ),
        migrations.AddField(
            model_name='portafolioprojects',
            name='technologies',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Portafolio_App.tecnologies'),
        ),
    ]
