# Generated by Django 5.1.4 on 2024-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0003_remove_portafolioprojects_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioprojects',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tecnologies',
            name='technologies_isDisabled',
            field=models.BooleanField(default=False, help_text='si la tecnologia esta deshabilitada'),
        ),
    ]
