# Generated by Django 5.1.4 on 2024-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0004_alter_portafolioprojects_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusproject',
            old_name='status_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tecnologies',
            old_name='technologies_isDisabled',
            new_name='disabled',
        ),
        migrations.RenameField(
            model_name='tecnologies',
            old_name='technologies_href',
            new_name='href',
        ),
        migrations.RenameField(
            model_name='tecnologies',
            old_name='technologies_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='portafolioprojects',
            name='date',
            field=models.DateField(auto_now=True, help_text='Fecha de creacion del proyecto'),
        ),
    ]
