# Generated by Django 5.1.4 on 2024-12-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0005_rename_status_title_statusproject_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Cargo del trabajo', max_length=255)),
                ('empresa', models.CharField(help_text='Empresa del trabajo', max_length=255)),
                ('descripcion', models.CharField(help_text='Descripcion del trabajo', max_length=255)),
                ('inicio', models.CharField(help_text='Fecha de inicio del trabajo', max_length=255)),
                ('fin', models.CharField(help_text='Fecha de fin del trabajo', max_length=255)),
                ('tareas', models.JSONField(help_text='Tareas del trabajo')),
            ],
        ),
    ]
