# Generated by Django 5.1.4 on 2024-12-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0006_portafolioworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolioworks',
            name='tareas',
            field=models.CharField(help_text='Tareas del trabajo', max_length=255),
        ),
    ]
