# Generated by Django 5.1.4 on 2024-12-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0007_alter_portafolioworks_tareas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolioworks',
            name='tareas',
        ),
    ]
