# Generated by Django 5.1.4 on 2024-12-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio_App', '0008_remove_portafolioworks_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolioworks',
            name='tareas',
            field=models.JSONField(default=list, help_text='Tareas del trabajo'),
        ),
    ]
